from pathlib import Path

import pytest

from classcorpus.citations import format_citation, format_timestamp
from classcorpus.claims import check_claims
from classcorpus.database import Database
from classcorpus.flashcards import Flashcard
from classcorpus.indexer import sync_course
from classcorpus.outline import outline_course
from classcorpus.parsers import parse_source, supported_suffixes
from classcorpus.provenance import verify_artifact, write_artifact_manifest
from classcorpus.record_text import read_record_text
from classcorpus.records import read_records
from classcorpus.search import search
from classcorpus.study_progress import identify_cards


def test_webvtt_parser_preserves_cues_and_timestamps(tmp_path: Path):
    source = tmp_path / "lecture.vtt"
    source.write_text(
        "WEBVTT - Physics captions\n"
        "Kind: captions\n\n"
        "NOTE generated by the recorder\n"
        "This block is metadata.\n\n"
        "intro\n"
        "00:00:01.000 --> 00:00:04.250 align:start\n"
        "<v Professor>Impulse changes momentum.</v>\n\n"
        "00:14:32.500 --> 00:14:36.000\n"
        "Energy is conserved &amp; transferred.\n",
        encoding="utf-8",
    )

    records = parse_source(source, tmp_path / "renders")

    assert supported_suffixes().issuperset({".vtt", ".srt"})
    assert [(record.start_ms, record.end_ms) for record in records] == [
        (1_000, 4_250),
        (872_500, 876_000),
    ]
    assert all(record.kind == "transcript" for record in records)
    assert records[0].body_text == "Impulse changes momentum."
    assert records[0].raw_text == "<v Professor>Impulse changes momentum.</v>"
    assert records[1].body_text == "Energy is conserved & transferred."


def test_srt_parser_accepts_bom_crlf_ids_and_comma_milliseconds(tmp_path: Path):
    source = tmp_path / "seminar.srt"
    source.write_bytes(
        (
            "\ufeff1\r\n"
            "00:00:02,125 --> 00:00:05,900\r\n"
            "First line\r\nSecond line\r\n\r\n"
            "custom-id\r\n"
            "01:02:03,500 --> 01:02:06,000\r\n"
            "Long lecture cue\r\n"
        ).encode("utf-8")
    )

    records = parse_source(source, tmp_path / "renders")

    assert records[0].body_text == "First line\nSecond line"
    assert records[0].start_ms == 2_125
    assert records[1].start_ms == 3_723_500
    assert format_timestamp(records[1].start_ms) == "01:02:03.500"


@pytest.mark.parametrize(
    ("suffix", "content", "message"),
    [
        (".vtt", "not a vtt\n", "must start with WEBVTT"),
        (
            ".srt",
            "1\n00:00:05,000 --> 00:00:04,000\nBackwards\n",
            "must end after it starts",
        ),
        (".srt", "1\nNo time here\n", "has no timing line"),
        (
            ".srt",
            "1\n00:00:05,000 --> 00:00:06,000\nLater\n\n"
            "2\n00:00:04,000 --> 00:00:05,000\nEarlier\n",
            "strictly increasing",
        ),
    ],
)
def test_transcript_parser_rejects_invalid_input(
    tmp_path: Path,
    suffix: str,
    content: str,
    message: str,
):
    source = tmp_path / f"invalid{suffix}"
    source.write_text(content, encoding="utf-8")

    with pytest.raises(ValueError, match=message):
        parse_source(source, tmp_path / "renders")


def test_timestamp_citations_work_end_to_end(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    monkeypatch.setenv("CLASSCORPUS_DATA_DIR", str(tmp_path / "state"))
    course_root = tmp_path / "course"
    course_root.mkdir()
    (course_root / "lecture.vtt").write_text(
        "WEBVTT\n\n"
        "00:00:01.000 --> 00:00:04.250\n"
        "Impulse changes momentum.\n\n"
        "00:14:32.500 --> 00:14:36.000\n"
        "Energy is conserved and transferred.\n",
        encoding="utf-8",
    )
    database = Database(tmp_path / "index.sqlite3")
    database.initialize()

    report = sync_course(database, "Physics", course_root)
    results = search(database, "impulse momentum", course="Physics")
    records = read_records(
        database,
        course="Physics",
        source_file="lecture.vtt",
        limit=10,
    )
    text = read_record_text(
        database,
        course="Physics",
        source_file="lecture.vtt",
        ordinal=1,
    )
    outline = outline_course(database, course="Physics", budget_tokens=10_000)

    assert report.indexed == 1
    assert report.records_indexed == 2
    assert format_citation(results[0]) == "[Physics, lecture.vtt, 00:01]"
    assert records.records[0].kind == "transcript"
    assert records.records[0].start_ms == 1_000
    assert records.records[1].end_ms == 876_000
    assert text.kind == "transcript"
    assert text.citation == "[Physics, lecture.vtt, 00:01]"
    assert outline["coverage"][0]["kind"] == "transcript"
    assert outline["coverage"][0]["citation_start"].endswith("00:01]")
    assert outline["coverage"][0]["citation_end"].endswith("14:32.500]")

    citation_source = tmp_path / "guide.md"
    citation_source.write_text(
        "Impulse changes momentum. [Physics, lecture.vtt, 00:01]\n",
        encoding="utf-8",
    )
    claims = check_claims(database, citation_source)
    artifact = tmp_path / "guide.html"
    artifact.write_text("<h1>Impulse</h1>", encoding="utf-8")
    manifest = write_artifact_manifest(
        database,
        artifact=artifact,
        citation_source=citation_source,
    )

    assert claims["ok"] is True
    assert claims["counts"]["supported"] == 1
    assert manifest["unresolved_citations"] == []
    assert manifest["citations"][0]["kind"] == "transcript"
    assert manifest["citations"][0]["start_ms"] == 1_000
    assert verify_artifact(database, artifact)["status"] == "current"
    card = Flashcard(
        "What changes momentum?",
        "Impulse.",
        "[Physics, lecture.vtt, 00:01]",
    )
    assert identify_cards(database, [card])[0].source_sha256
